name: 'reconciliation_engine'
version: '1.0.0'
config-version: 2

profile: 'reconciliation_engine'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  reconciliation_engine:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts 