# Configuration for Reconciliation Engine

matching:
  internal_key: "amount"
  external_key: "net_amount"
  match_on:
    - "date"
    - "customer_id"
    - "location_id"

tolerances:
  amount: 0.05    # dollar tolerance
  days: 1         # date tolerance in days

output:
  path: "outputs"
  reconciled_file: "reconciled.csv"
  unmatched_internal_file: "unmatched_internal.csv"
  unmatched_external_file: "unmatched_external.csv"
